Index/启发式搜索.md
Index/图论 BFS.md
LeetCode/751-760/752. 打开转盘锁（中等）.md
LeetCode/771-780/773. 滑动谜题（困难）.md

✨feat: Add 773 & Modify 752

---

Index/图论 BFS.md
LeetCode/811-820/815. 公交路线（困难）.md
LeetCode/901-910/909. 蛇梯棋（中等）.md

✨feat: Add 815 & Modify 909

---

Index/图论 BFS.md
LeetCode/1051-1160/1162. 地图分析（中等）.md

✨feat: Add 1162

---

Index/BFS.md
Index/二叉树.md
LeetCode/291-300/297. 二叉树的序列化与反序列化（困难）.md
LeetCode/剑指 Offer/剑指 Offer 37. 序列化二叉树（困难）.md

✨feat: Add 剑指 Offer 37、297

---

LeetCode/LCP/LCP 07. 传递信息（简单）.md

✨fix: Update LCP 07

---

Index/位运算.md
Index/哈希表.md
LeetCode/1711-1720/1711. 大餐计数（中等）.md

✨feat: Add 1711

---

LeetCode/211-220/218. 天际线问题（困难）.md

✨feat: Modify 218

---

Index/哈希表.md
Index/打表.md
Index/排序.md
Index/数学.md
Index/模拟.md
LeetCode/面试题/面试题 10.02. 变位词组（中等）.md

✨feat: Add 面试题 10.02

---

LeetCode/面试题/面试题 10.02. 变位词组（中等）.md

✨feat: Modify 面试题 10.02

---

Index/链表.md
LeetCode/1871-1880/1877. 数组中最大数对和的最小值（中等）.md
LeetCode/剑指 Offer/剑指 Offer 52. 两个链表的第一个公共节点（简单）.md

✨feat: Add 剑指 Offer 52

---

Index/树状数组.md
Index/模拟.md
Index/线段树.md
LeetCode/1891-1900/1893. 检查是否区域内所有整数都被覆盖（简单）.md

✨feat: Add 1893

---

Index/图论：最短路.md
LeetCode/741-750/743. 网络延迟时间（中等）.md

✨feat: Add 743

---

LeetCode/741-750/743. 网络延迟时间（中等）.md

✨feat: Modify 743

---

LeetCode/521-530/525. 连续数组（中等）.md

✨Update: Modify 525

---

LeetCode/521-530/526. 优美的排列（中等）.md

✨Update: Modify 526

---

LeetCode/551-560/552. 学生出勤记录 II（困难）.md

✨Update: Modify 552

---

LeetCode/1711-1720/1713. 得到子序列的最少操作次数（困难）.md

✨Update: Modify 1713

---

LeetCode/1-10/6. Z 字形变换（中等）.md

✨Update: Modify 6

---

LeetCode/641-650/645. 错误的集合（简单）.md

✨Update: Modify 645

---

LeetCode/541-550/541. 反转字符串 II（简单）.md

✨Update: Modify 541

---

Index/打表.md
LeetCode/1641-1650/1646. 获取生成数组中的最大值（简单）.md

✨Update: Modify 1646

---

Index/图论：最短路.md
LeetCode/781-790/787. K 站中转内最便宜的航班（中等）.md

✨feat: Add 787

---

Index/序列 DP.md
LeetCode/1471-1480/1473. 粉刷房子 III（困难）.md

✨Update: Modify 1473

---

Index/差分.md
Index/线段树.md
LeetCode/1101-1110/1109. 航班预订统计（中等）.md

✨feat: Add 1109

---

Index/堆.md
Index/排序.md
LeetCode/面试题/面试题 17.14. 最小K个数（中等）.md

✨feat: Add 面试题 17.14

---

LeetCode/剑指 Offer/剑指 Offer 10- I. 斐波那契数列（简单）.md

✨update: Modify 剑指 Offer 10- I

✨update: Modify 剑指 Offer 10- I

---

LeetCode/741-750/743. 网络延迟时间（中等）.md

✨update: Modify 743

---

LeetCode/441-450/447. 回旋镖的数量（中等）.md

✨feat: Add 447

---

LeetCode/421-430/430. 扁平化多级双向链表（中等）.md

✨update: Modify 430

---

LeetCode/281-290/284. 顶端迭代器（中等）.md

✨feat: Add 284

---

Index/图论 BFS.md
LeetCode/2051-2060/2059. 转化数字的最小运算数（中等）.md

✨feat: Add 2059

---

LeetCode/621-630/629. K个逆序对数组（困难）.md

✨update: Modify 629

---

LeetCode/371-380/375. 猜数字大小 II（中等）.md

✨update: Modify 375

---

LeetCode/671-680/677. 键值映射（中等）.md

✨update: Modify 677

---

Index/扫描线问题.md
LeetCode/391-400/391. 完美矩形（困难）.md

✨feat: Add 391

---

LeetCode/311-320/318. 最大单词长度乘积（中等）.md

✨update: Modify 318

---

LeetCode/591-600/594. 最长和谐子序列（简单）.md

✨update: Modify 594

---

Index/洗牌算法.md
LeetCode/381-390/384. 打乱数组（中等）.md

✨feat: Add 384

---

LeetCode/391-400/400. 第 N 位数字（中等）.md

✨update: Modify 400

---

LeetCode/371-380/372. 超级次方（中等）.md

✨feat: Add 372

---

LeetCode/1811-1820/1816. 截断句子（简单）.md

✨update: Modify 1816

---

LeetCode/1031-1040/1034. 边界着色（中等）.md

✨update: Modify 1034

---

Index/图论：拓扑排序.md
LeetCode/851-860/851. 喧闹和富有（中等）.md

✨feat: Add 851

---

LeetCode/1701-1710/1705. 吃苹果的最大数目（中等）.md

✨update: Modify 1705

---

Index/回溯算法.md
Index/高精度.md
LeetCode/301-310/306. 累加数（中等）.md

✨feat: Add 306

---

LeetCode/531-540/539. 最小时间差（中等）.md

✨update: Modify 539

---

Index/图论 BFS.md
LeetCode/1341-1350/1345. 跳跃游戏 IV（困难）.md

✨feat: Add 1345

---

LeetCode/1341-1350/1345. 跳跃游戏 IV（困难）.md

✨update: Modify 1345

---

LeetCode/2051-2060/2059. 转化数字的最小运算数（中等）.md

✨update: Modify 2059

---

LeetCode/811-820/815. 公交路线（困难）.md

✨update: Modify 815

---

LeetCode/751-760/752. 打开转盘锁（中等）.md

✨update: Modify 752

---

LeetCode/121-130/127. 单词接龙（困难）.md

✨update: Modify 127

---

LeetCode/481-490/488. 祖玛游戏（困难）.md

✨update: Modify 488

---

LeetCode/2031-2040/2034. 股票价格波动（中等）.md

✨update: Modify 2034

---

LeetCode/1761-1770/1765. 地图中的最高点（中等）.md

✨update: Modify 1765

---

Index/回溯算法.md
LeetCode/1211-1220/1219. 黄金矿工（中等）.md

✨feat: Add 1219

---

LeetCode/371-380/373. 查找和最小的K对数字（中等）.md
LeetCode/421-430/424. 替换后的最长重复字符（中等）.md
LeetCode/991-1000/992. K 个不同整数的子数组（困难）.md

✨update: Modify 992、424、373

---

LeetCode/371-380/373. 查找和最小的K对数字（中等）.md

✨update: Modify 373

---

LeetCode/311-320/313. 超级丑数（中等）.md

✨update: Modify 313

---

Index/区间 DP.md
Index/单调栈.md
LeetCode/2101-2110/2104. 子数组范围和（中等）.md

✨feat: Add 2104

---

LeetCode/1101-1110/1109. 航班预订统计（中等）.md

✨update: Modify 1109

---

Index/差分.md
LeetCode/791-800/798. 得分最高的最小轮调（困难）.md

✨feat: Add 798

---

Index/图论 DFS.md
LeetCode/2041-2050/2049. 统计最高分的节点数目（中等）.md

✨feat: Add 2049

---

LeetCode/2041-2050/2049. 统计最高分的节点数目（中等）.md
LeetCode/581-590/590. N 叉树的后序遍历（简单）.md

✨update: Modify 2049

---

LeetCode/711-720/717. 1比特与2比特字符（简单）.md

✨update: Modify 717

---

LeetCode/2041-2050/2043. 简易银行系统（中等）.md

✨update: Modify 2043

---

LeetCode/2031-2040/2039. 网络空闲的时刻（中等）.md

✨update: Modify 2039

---

LeetCode/681-690/682. 棒球比赛（简单）.md

✨update: Modify 682

---

LeetCode/411-420/420. 强密码检验器（困难）.md

✨update: Modify 420

---

Index/线段树.md
LeetCode/301-310/307. 区域和检索 - 数组可修改（中等）.md

✨update: Modify 307

---

Index/栈.md
Index/链表.md
LeetCode/面试题/面试题 02.05. 链表求和（中等）.md

✨feat: Add 面试题 02.05

---

Index/哈希表.md
LeetCode/剑指 Offer II/剑指 Offer II 030. 插入、删除和随机访问都是 O(1) 的容器（中等）.md

✨feat: Add 剑指 Offer II 030

---

Index/并查集.md
LeetCode/411-420/417. 太平洋大西洋水流问题（中等）.md

✨feat: Add 417

---

LeetCode/591-600/591. 标签验证器（困难）.md

✨feat: Add 591

---

LeetCode/431-440/433. 最小基因变化（中等）.md

✨feat: Add 433

---

Index/博弈论.md
Index/记忆化搜索.md
LeetCode/1721-1730/1728. 猫和老鼠 II（困难）.md

✨feat: Add 1728

---

LeetCode/121-130/127. 单词接龙（困难）.md
LeetCode/431-440/433. 最小基因变化（中等）.md

✨style: Bulk processing format

✨style: Bulk processing format

---

Index/模拟.md
LeetCode/811-820/812. 最大三角形面积（简单）.md

✨feat: Add 812

---

LeetCode/1231-1240/1239. 串联字符串的最大长度（中等）.md
LeetCode/1721-1730/1723. 完成所有工作的最短时间（困难）.md
LeetCode/471-480/473. 火柴拼正方形（中等）.md

✨feat: add 1239、1723、473

---

LeetCode/731-740/732. 我的日程安排表 III（困难）.md

✨feat: add 732

---

LeetCode/691-700/699. 掉落的方块（困难）.md

699.掉落的方块（困难）题解的题目链接有错误，现在已经改过来了。
三叶姐，这样应该能合并了吧，第一次提pr，学了好久还搞错了。233333

Update 699. 掉落的方块（困难）.md

---

LeetCode/691-700/699. 掉落的方块（困难）.md

699.掉落的方块（困难）修改了题解链接

---

LeetCode/921-930/926. 将字符串翻转到单调递增（中等）.md

✨feat: add 926

---

Index/线段树.md
LeetCode/711-720/715. Range 模块（困难）.md
LeetCode/721-730/729. 我的日程安排表 I（中等）.md
LeetCode/731-740/731. 我的日程安排表 II（中等）.md
LeetCode/731-740/732. 我的日程安排表 III（困难）.md

✨feat: add 715

---

Index/图论：拓扑排序.md
LeetCode/201-210/207. 课程表（中等）.md

✨feat: add 207

---

LeetCode/731-740/736. Lisp 语法解析（困难）.md

✨feat: add 736

---

Index/字典树.md
LeetCode/741-750/745. 前缀和后缀搜索（困难）.md

✨feat: add 745

---

Index/模拟.md
Index/队列.md
LeetCode/剑指 Offer II/剑指 Offer II 041. 滑动窗口的平均值（简单）.md

✨feat: add Offer II 041

---

Index/图论 拓扑排序.md
Index/构造.md
LeetCode/剑指 Offer II/剑指 Offer II 115. 重建序列（中等）.md

✨feat: Offer II 115

---

Index/BFS.md
LeetCode/1161-1170/1161. 最大层内元素和（中等）.md

✨feat: add 1161

---

LeetCode/1371-1380/1374. 生成每种字符都是奇数个的字符串（简单）.md

✨feat: add 1818

---

Index/队列.md
LeetCode/621-630/622. 设计循环队列（中等）.md

✨feat: add 622

---

Index/数学.md
Index/模拟.md
LeetCode/剑指 Offer/剑指 Offer 44. 数字序列中某一位的数字（中等）.md

✨feat: add 剑指 Offer 44

---

Index/差分.md
LeetCode/1441-1450/1450. 在既定时间做作业的学生人数（简单）.md

✨feat: add 1450

---

Index/前缀和.md
Index/哈希表.md
LeetCode/剑指 Offer II/剑指 Offer II 011. 0 和 1 个数相同的子数组（中等）.md

✨feat: 剑指 Offer II 011

---

Index/前缀和.md
Index/哈希表.md
LeetCode/剑指 Offer II/剑指 Offer II 010. 和为 k 的子数组（中等）.md

✨feat: 剑指 Offer II 010

---

Index/双指针.md
Index/滑动窗口.md
LeetCode/剑指 Offer II/剑指 Offer II 009. 乘积小于 K 的子数组（中等）.md

✨feat: 剑指 Offer II 009

---

Index/二分.md
Index/前缀和.md
Index/双指针.md
Index/排序.md
LeetCode/剑指 Offer II/剑指 Offer II 007. 数组中和为 0 的三个数（中等）.md
LeetCode/剑指 Offer II/剑指 Offer II 008. 和大于等于 target 的最短子数组（中等）.md

✨feat: 剑指 Offer II 007

---

LeetCode/781-790/782. 变为棋盘（困难）.md

✨feat: add 782

---

LeetCode/991-1000/998. 最大二叉树 II（中等）.md

✨feat: add 998

---

LeetCode/1181-1190/1190. 反转每对括号间的子串（中等）.md

✨feat: add 1190

---

Index/字典树.md
LeetCode/1031-1040/1032. 字符流（困难）.md

✨feat: add 1032

---

Index/找规律.md
LeetCode/671-680/672. 灯泡开关 Ⅱ（中等）.md

✨feat: add 672

---

Index/扫描线问题.md
LeetCode/391-400/391. 完美矩形（困难）.md
LeetCode/841-850/850. 矩形面积 II（困难）.md

✨feat: add 391 & 850

---

Index/数学.md
LeetCode/面试题/面试题 17.19. 消失的两个数字（困难）.md

✨feat: add 面试题 17.19

---

Index/模拟.md
LeetCode/面试题/面试题 01.08. 零矩阵（中等）.md

✨feat: add 面试题 01.08

---

LeetCode/881-890/886. 可能的二分法（中等）.md

请在typescript中使用闭包或者类,不要修改共享全局变量
为何不建议使用全局变量?
https://zhuanlan.zhihu.com/p/59636541

请在typescript中使用闭包,不要修改共享全局变量

---

LeetCode/861-870/862. 和至少为 K 的最短子数组（困难）.md

✨feat: add 862

---

Index/状态机 DP.md
Index/线性 DP.md
LeetCode/191-200/198. 打家劫舍（中等）.md

✨feat: add 198

---

Index/模拟.md
LeetCode/811-820/816. 模糊坐标（中等）.md

✨feat: add 816

---

Index/构造.md
Index/模拟.md
LeetCode/791-800/791. 自定义字符串排序（中等）.md

✨feat: add 791

---

README.md

✨update: readme

---

Index/状压 DP.md
LeetCode/2301-2310/2305. 公平分发饼干（中等）.md

✨feat: add 2305
